### ISSUE TITLE
 java.lang.UnsatisfiedLinkError,  couldn't find "libopen_dsm.so"

### ISSUE THREAD

**Issue by Hemedy** [biezhihua/libdsm#15]
Am getting this error, when I run the app.Any help I would appreciate.
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/.....-1/base.apk"],nativeLibraryDirectories=[/data/app/....-1/lib/x86_64, /vendor/lib64, /system/lib64]]] couldn't find "libopen_dsm.so"

**Comment by biezhihua** [comment]
Let me see.

**Comment by Hemedy** [comment]
Sure , I will appreciate.

**Comment by Hemedy** [comment]
![image](https://user-images.githubusercontent.com/32874926/122945955-9fca2880-d381-11eb-9d5b-de1fd0c6f5e0.png)
I have done some research, it seems to revolve around here

**Comment by biezhihua** [comment]
I already support all the Android architectures, you can update the code

**Comment by biezhihua** [comment]
@Hemedy
