### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Hemedy** [biezhihua/libdsm#16]
I am unable to login. Its says "Unable to perform name resolution for...."
![image](https://user-images.githubusercontent.com/32874926/123795908-30a68400-d8ed-11eb-9db3-1e9ef34a50f2.png)

**Comment by Hemedy** [comment]
Hello @biezhihua, are you there? l would appreciate your help again

**Comment by biezhihua** [comment]
@Hemedy Sorry for the late reply, I will check this issue as soon as possible

**Comment by Hemedy** [comment]
@biezhihua sure thank you, I am doing an app, I wall have to pause and wait for you feedback.

**Comment by Hemedy** [comment]
HI @biezhihua, I know is much to ask, am stuck here, How long might it take?

**Comment by biezhihua** [comment]
Sorry, I'm afraid it will be a little slower. I have a lot of routine work to do.

I could take some time off this weekend to look at the problem, but I'm not sure I'll be able to finish it.

**Comment by biezhihua** [comment]
Please post a more detailed text log, do not delete the printed log content, otherwise I will not be able to determine some problems.

@Hemedy

**Comment by Hemedy** [comment]
I/DsmPlugin( 3010): onMethodCall() called with: call.method = [DSM_login], call.args = [{password=madi, id=71877913-cd4e-40f7-9835-ebcf3cb21fdb, login_name=Kali, host=192.168.1.106}]
E/[DSM][NATIVE]( 3010): [login] Unable to perform name resolution for 192.168.1.106
I/flutter ( 3010): numb -1
I/DsmPlugin( 3010): onMethodCall() called with: call.method = [DSM_tree_connect], call.args = [{name=share, id=71877913-cd4e-40f7-9835-ebcf3cb21fdb}]
E/[DSM][NATIVE]( 3010): [treeConnect] Please login
I/flutter ( 3010): treeInt -100
I/DsmPlugin( 3010): onMethodCall() called with: call.method = [DSM_start_discovery], call.args = [{time_out=30, id=71877913-cd4e-40f7-9835-ebcf3cb21fdb}]
D/[DSM][NATIVE]( 3010): [DSM_startDiscovery] Start discovering ...
I/DsmPlugin( 3010): onCancel() called with: arguments = [null]
I/DsmPlugin( 3010): onListen() called with: arguments = [71877913-cd4e-40f7-9835-ebcf3cb21fdb], events = [io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation@3ad57a60]
I/DsmPlugin( 3010): onMethodCall() called with: call.method = [DSM_get_share_list], call.args = [{id=71877913-cd4e-40f7-9835-ebcf3cb21fdb}]
E/[DSM][NATIVE]( 3010): [shareGetList] Please login
E/[DSM][NATIVE]( 3010): [DSM_shareGetListJson] Share get list failed


@biezhihua

**Comment by biezhihua** [comment]
```
login(hostName: String, loginName: String, password: String)
```

To log in, translate the host address to the host name by using the inverse() method

**Comment by biezhihua** [comment]
@Hemedy
