### ISSUE TITLE
Help on reading video file.

### ISSUE THREAD

**Issue by ghost** [biezhihua/libdsm#2]
@biezhihua I import your example flutter project, and could login, and treeConnect to shared folder.
But when I tried to read file, it can't not connect to the file.

Could you show me how to read file. We need to read .mp4 file in smb server, and display it on flutter app.

**Comment by biezhihua** [comment]
Hello, in fact, LIBDSM Naitve Library has realized the function of opening files, but my Wrapper library does not support it.

This requires writing code such as C++, iOS, Android, etc. before it can be supported.


Unfortunately, although I know how to do it, I don’t have enough time to do it.

If you have any questions, you can add my Wechat: biezhihua


Also hope you can submit some code for this library.

https://videolabs.github.io/libdsm/
```
  fd = smb_fopen(session, tid, "\\My\\File");
  if (!fd)
  {
    printf("Unable to open file\n");
    exit(5);
  }

  char buffer[512];
  smb_fread(session, fd, buffer, 512);

  /* Use data */

```
