### ISSUE TITLE
dsm find and treedisconnect error

### ISSUE THREAD

**Issue by Nillouise** [biezhihua/libdsm#4]
I run the example code,other function is work fine, treeConnect work and return tid is 54349, but use this tid to call dsm.find function, it will throw error(also the treedisconnect also error).

I/DsmPlugin(19194): onMethodCall() called with: call.method = [DSM_find], call.args = [{pattern=\*, id=68be45c6-9ba0-4fa0-908f-875da9bdb115, tid=54349}]
E/flutter (19194): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(PARAM_ERROR, Illegal parameter, null)
E/flutter (19194): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (19194): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (19194): <asynchronous suspension>
E/flutter (19194): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (19194): #3      Dsm.find (package:libdsm/libdsm.dart:188:46)
E/flutter (19194): #4      _MyAppState._find (package:raising/main.dart:91:31)
E/flutter (19194): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (19194): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (19194): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (19194): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (19194): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (19194): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)

**Comment by Nillouise** [comment]
currently I fix it by change DsmPlugin.kt file's  call.argument<Int>(TID) != 0  to  call.argument<Int>(TID) == null, now it work fine.

but after that I dicover the find result didn't contain the file create timestamp and not sort by timestamp, it's lack a core feature.

**Comment by biezhihua** [comment]
@Nillouise 

Thank you for your feedback.

The current libDSM does lack some features, but since the whole link has been opened up, it is convenient to add other features.

I hope I can make some Pull requests for this library.

thank you

**Comment by biezhihua** [comment]
Hope you can mention PR to fix this...

**Comment by Nillouise** [comment]
I can fix this bug by make a pr if it really a bug(insetead of my environment issue).

I have try to add some method to this library, but I am new to android, I even dont know how this library can run with C and ndk... if there is some tutorial would be helpful

**Comment by biezhihua** [comment]
fixed 

https://github.com/biezhihua/libdsm/commit/ce343e9e890b10324d203b11b40c155f0b0ccbac
