### ISSUE TITLE
_fileStatus not working in android

### ISSUE THREAD

**Issue by sathishmscict** [biezhihua/libdsm#7]
onMethodCall() called with: call.method = [DSM_file_status], call.args = [{id=2c3c8682-174c-490d-913f-58fe98ed2e2f, path=\Mscict\Resume1.doc, tid=2062}]
E/flutter (16391): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(PARAM_ERROR, Illegal parameter, null)
E/flutter (16391): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (16391): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (16391): <asynchronous suspension>
E/flutter (16391): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (16391): #3      Dsm.fileStatus (package:libdsm/libdsm.dart:204:46)
E/flutter (16391): #4      _MyAppState._fileStatus (package:example_flutter/main.dart:84:31)
E/flutter (16391): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (16391): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (16391): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (16391): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (16391): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (16391): #10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
E/flutter (16391): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (16391): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (16391): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (16391): #14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (16391): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (16391): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (16391): #17     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (16391): #18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (16391): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (16391): #20     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (16391): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter (16391): 

Here , Mscict is shared folder.
Resume1.doc is doc inside shared folder.       

Code : 
    void _fileStatus() async {
        //String result = await dsm.fileStatus(tid, "\\splayer\\splayer_soundtouch\\Test.cpp");
        String result = await dsm.fileStatus(tid, "\\Mscict\\Resume1.doc");
      }

**Comment by Mi2Sir** [comment]
I encounter the same " [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(PARAM_ERROR, Illegal parameter, null)" error when calling  DSM_find and DSM_fileStatus methods for android.
Is there any solution for this problem?

**Comment by Mi2Sir** [comment]
> I encounter the same " [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(PARAM_ERROR, Illegal parameter, null)" error when calling DSM_find and DSM_fileStatus methods for android.
> Is there any solution for this problem?

I found the problem have been solved in DsmPlugin.kt, but flutter pub get / upgrade haven't been updated.
