### ISSUE TITLE
Error found when calling dsm.startDiscovery

### ISSUE THREAD

**Issue by Mi2Sir** [biezhihua/libdsm#9]
I enconter the following error in flutter when calling dsm.startDiscovery.

E/libc++abi(18532): terminating with uncaught exception of type nlohmann::detail::type_error: [json.exception.type_error.316] invalid UTF-8 byte at index 3: 0xD7

Any idea ? How to solve the problem?

**Comment by biezhihua** [comment]
Can you post the DSM device you linked to when this error occurred

**Comment by Mi2Sir** [comment]
I know It's the problem of the device. 
When calling dsm.inverse(192.168.1.126) , it return  null value means it doesn't have a share name.
I don't know how to get rid of the device when i call dsm.startDiscovery.

**Comment by biezhihua** [comment]
这里是错误原因：https://blog.csdn.net/qq_42896627/article/details/108255869

在启动发现之后，搜索到了DSM主机，但是主机名称不是UTF-8的编码，从而出错

**Comment by biezhihua** [comment]
@Mi2Sir 这个问题，最近一两周我会修复一下

**Comment by Mi2Sir** [comment]
> @Mi2Sir 这个问题，最近一两周我会修复一下

謝謝你
